global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:

rule_files:


scrape_configs:
  - job_name: "Omada_Exporter"
    metrics_path: "/appmetrics"
    static_configs:
      - targets: [
          "apps.Horna.local:51772"
        ]
  - job_name: "SpeedTest_Exporter"
    metrics_path: "/appmetrics"
    static_configs:
      - targets: [
          "apps.Horna.local:8000"
        ]
  
  - job_name: "Tempo"
    static_configs:
      - targets: [
          "apps.Horna.local:3200"
        ]

  - job_name: "Loki"
    static_configs:
      - targets: [
          "apps.Horna.local:3111",
          "services.Horna.local:3100"
        ]
  
  - job_name: "Prometheus"
    static_configs:
      - targets: [
          "apps.Horna.local:9999",
          "services.Horna.local:9090"
        ]

  - job_name: "Grafana"
    static_configs:
      - targets: [
          "apps.Horna.local:3000"
        ]
