global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:

rule_files:


scrape_configs:
  - job_name: "Omada_Exporter"
    metrics_path: "/appmetrics"
    static_configs:
      - targets: [
          "dockerserver.Horna.local:51772"
        ]